### PR TITLE
Correcting the ascii encode error

### PR DESCRIPTION
**Pull request by paje**

### CODE REVIEW

**Comment by x0rz** [comment]
Thanks for the PR 👍
I'm not sure what bug this is trying to fix, could you please explain so I can reproduce?

**Comment by packetrat** [comment]
at install on Debian 8, with Python 2.7.9:
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-QV1Swq/ascii-graph/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-thU3m7-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-QV1Swq/ascii-graph

**Comment by delk0** [comment]
I believe he's trying to fix this (happening on Windows 10, at least)

test

**Comment by ozzi-** [comment]
This is not a bug. Windows default terminal does not support ansi color codes. 
One could make the app aware of the running OS

**Pull request closed without merging**
